---
# CACC SCENARIOS

open_straight_road:
  lanes: straight_road
  actors: []
  ego: {make: cadillac_lyriq, lane_id: 0}
  controller: cacc

straight_road_lead_vehicle_ftp:
  lanes: straight_road
  actors:
    - lead: {make: tesla_model3, lane_id: 0, offset: 50, speed_profile: ftp75}
  ego: {make: cadillac_lyriq, lane_id: 0}
  controller: cacc